; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Thu Dec 29 2016 23:38:47 GMT-0800 (Pacific Standard Time)

; Wait for set temperatures to be reached
; M116 P0
